Update conexao

diff --git a/Modulos/conexao b/Modulos/conexao
--- a/Modulos/conexao
+++ b/Modulos/conexao
@@ -464,9 +464,9 @@
 
 	inst_ssl() {
 		if netstat -nltp | grep 'stunnel4' 1>/dev/null 2>/dev/null; then
-			[[ $(netstat -nltp | grep 'stunnel4' | wc -l) != '0' ]] && sslt=$(netstat -nplt | grep stunnel4 | awk {'print $4'} | awk -F ":" {'print $2'} | xargs) || sslt="\033[1;31mINDISPONIVEL"
+			[[ $(netstat -nltp | grep 'stunnel4' | wc -l) != '0' ]] && sslt=$(netstat -nplt | grep stunnel4 | awk {'print $4'} | awk -F ":" {'print $2'} | xargs) || sslt="\033[1;31mNEPASIEKIAMAS"
 			echo -e "\E[44;1;37m              MANAGE SSL TUNNEL               \E[0m"
-			echo -e "\n\033[1;33mPORTS\033[1;37m: \033[1;32m$sslt"
+			echo -e "\n\033[1;33mPORTAS\033[1;37m: \033[1;32m$sslt"
 			echo ""
 			echo -e "\033[1;31m[\033[1;36m1\033[1;31m] \033[1;37m• \033[1;33mCHANGE SSL TUNNEL PORT\033[0m"
 			echo -e "\033[1;31m[\033[1;36m2\033[1;31m] \033[1;37m• \033[1;33mREMOVE SSL TUNNEL\033[0m"
@@ -496,7 +496,7 @@
 				echo -e "\033[1;32mRESTARTING SSL TUNNEL!\n"
 				fun_bar 'service stunnel4 restart' '/etc/init.d/stunnel4 restart'
 				echo ""
-				netstat -nltp | grep 'stunnel4' >/dev/null && echo -e "\033[1;32mPORT CHANGED SUCCESSFULLY !" || echo -e "\033[1;31mUNEXPECTED ERROR!"
+				netstat -nltp | grep 'stunnel4' >/dev/null && echo -e "\033[1;32mPORT CHANGED SUCCESSFULLY !" || echo -e "\033[1;31mNETIKETA KLAIDA!"
 				sleep 3.5s
 				clear
 				fun_conexao
@@ -515,7 +515,7 @@
 				echo ""
 				fun_bar 'del_ssl'
 				echo ""
-				echo -e "\033[1;32mSUCCESSFULLY REMOVED SSL TUNNEL!\033[0m"
+				echo -e "\033[1;32mUCCESSFULLY REMOVED SSL TUNNEL!\033[0m"
 				sleep 3
 				fun_conexao
 			} || {
@@ -525,6 +525,30 @@
 			}
 		else
 			clear
+			echo -e "\E[44;1;37m              SSL TUNNEL INSTALLER               \E[0m"
+			echo ""
+			echo -e "\033[1;31m[\033[1;36m1\033[1;31m] \033[1;37m• \033[1;33mINSTALL SSL TUNNEL \033[0m"
+			echo -e "\033[1;31m[\033[1;36m2\033[1;31m] \033[1;37m• \033[1;33mINSTALL SSL TUNNEL WEBSOCKET\033[0m"
+			echo -e "\033[1;31m[\033[1;36m0\033[1;31m] \033[1;37m• \033[1;33mBACK\033[0m"
+			echo ""
+			echo -ne "\033[1;32mPLEASE SELECT FROM OPTIONS \033[1;33m?\033[1;37m "
+			read resposta
+			echo ""
+            if [[ "$resposta" = '1' ]]; then
+                portssl='22'
+            elif [[ "$resposta" = '2' ]]; then     
+                portssl='80'
+            elif [[ "$resposta" = '0' ]]; then
+				echo -e "\033[1;31mReturning...\033[0m"
+				sleep 3
+				fun_conexao
+            else
+			echo ""
+			echo -e "\033[1;31mInvalid port !\033[0m"
+			sleep 1
+			inst_ssl
+		fi
+            clear
 			echo -e "\E[44;1;37m           SSL TUNNEL INSTALLER             \E[0m"
 			echo -e "\n\033[1;33mYOU ARE ABOUT TO INSTALL SSL TUNNEL !\033[0m"
 			echo ""
@@ -533,7 +557,8 @@
 			[[ "$resposta" = 'y' ]] && {
 				echo -e "\n\033[1;33mDEFINE A PORT FOR SSL TUNNEL !\033[0m"
 				echo ""
-				read -p "$(echo -e "\033[1;32mWHICH PORT DO YOU WANT TO USE? \033[1;37m")" -e -i 443 porta
+				echo -ne "\033[1;32mWHICH PORT DO YOU WANT TO USE \033[1;33m?\033[1;37m "
+                read porta
 				[[ -z "$porta" ]] && {
 					echo ""
 					echo -e "\033[1;31mInvalid port!"
@@ -548,7 +573,7 @@
 				echo -e "\n\033[1;32mCONFIGURING SSL TUNNEL !\033[0m"
 				echo ""
 				ssl_conf() {
-					echo -e "cert = /etc/stunnel/stunnel.pem\nclient = no\nsocket = a:SO_REUSEADDR=1\nsocket = l:TCP_NODELAY=1\nsocket = r:TCP_NODELAY=1\n\n[stunnel]\nconnect = 0.0.0.0:22\naccept = ${porta}\nsslVersion = all" >/etc/stunnel/stunnel.conf
+					echo -e "cert = /etc/stunnel/stunnel.pem\nclient = no\nsocket = a:SO_REUSEADDR=1\nsocket = l:TCP_NODELAY=1\nsocket = r:TCP_NODELAY=1\n\n[stunnel]\nconnect = 127.0.0.1:$portssl\naccept = ${porta}" >/etc/stunnel/stunnel.conf
 				}
 				fun_bar 'ssl_conf'
 				echo -e "\n\033[1;32mCREATING CERTIFICATE !\033[0m"
